#ifndef INCLUDE_PIKA_VERSION_H_
#define INCLUDE_PIKA_VERSION_H_

#define PIKA_MAJOR 3
#define PIKA_MINOR 2
#define PIKA_PATCH 7
#define PIKA_BUILD_TIME ("201911251703")

#endif  // INCLUDE_PIKA_VERSION_H_
